### ISSUE TITLE
Fetching Payment Details 

### ISSUE THREAD

**Issue by naved997** [cashfree/cashfree-pg-sdk-java#59] opened 2024-05-08 12:34 UTC
I am trying to Fetching Payment Details by Java previously below code works fine and i got the response: 

`  ApiResponse<List<PaymentEntity>> response1 = cashfree.PGOrderFetchPayments("2023-08-01", orderid,null, null, null);
            List <PaymentEntity> paymentEntities = response1.getData();
            String paymentstatus="";
            String txnid="";
            String orderid1="";
            String paymentmode="";
            String amount="";

            for (int i = 0; i < paymentEntities.size(); i++) {
                paymentstatus= String.valueOf(paymentEntities.get(i).getPaymentStatus());
                txnid=paymentEntities.get(i).getCfPaymentId();
                orderid1=paymentEntities.get(i).getOrderId();
                paymentmode= String.valueOf(paymentEntities.get(i).getPaymentMethod().getPaymentMethodAppInPaymentsEntity().getApp().getProvider());
                amount= String.valueOf(paymentEntities.get(i).getOrderAmount());
            }`

But today i got the error:

**Message:** class com.cashfree.model.PaymentMethodUPIInPaymentsEntity cannot be cast to class com.cashfree.model.PaymentMethodAppInPaymentsEntity (com.cashfree.model.PaymentMethodUPIInPaymentsEntity and com.cashfree.model.PaymentMethodAppInPaymentsEntity are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @47fe85d4)

java.lang.ClassCastException: class com.cashfree.model.PaymentMethodUPIInPaymentsEntity cannot be cast to class com.cashfree.model.PaymentMethodAppInPaymentsEntity (com.cashfree.model.PaymentMethodUPIInPaymentsEntity and com.cashfree.model.PaymentMethodAppInPaymentsEntity are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @47fe85d4)

**Exception:**	com.cashfree.model.PaymentEntityPaymentMethod.getPaymentMethodAppInPaymentsEntity(PaymentEntityPaymentMethod.java:412)
	com.example.regalbiriyani.CashFreeConfirm.doGet(CashFreeConfirm.java:50)
	jakarta.servlet.http.HttpServlet.service(HttpServlet.java:683)
	jakarta.servlet.http.HttpServlet.service(HttpServlet.java:792)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	
Please check the issue i want to take the gateway to production.

**Comment by suhas-cashfree** [comment] 2024-05-08 12:39
Can you share the SDK version you are using

**Comment by naved997** [comment] 2024-05-08 12:42
SDK Version: 4.1.2

**Comment by naved997** [comment] 2024-05-08 12:42
The error occurs with all payment method.

**Comment by suhas-cashfree** [comment] 2024-05-08 12:52
The issue is here

`String.valueOf(paymentEntities.get(i).getPaymentMethod().getPaymentMethodAppInPaymentsEntity().getApp().getProvider());`

`paymentEntities.get(i).getPaymentMethod()` can have value of upi, wallet, netbanking, card object. And you trying to type cast to Wallet Payment for any transaction.

You have to check which instance it belongs to and then do getProvider().

**Comment by naved997** [comment] 2024-05-08 12:55
How can i do this? Previously this same code works you gave this code.

**Comment by suhas-cashfree** [comment] 2024-05-08 12:55
Do something like this
`if(Objects.requireNonNull(response.getData().get(i).getPaymentMethod()).getActualInstance() instanceof PaymentMethodAppInPaymentsEntity) {
                    System.out.println(Objects.requireNonNull(Objects.requireNonNull(response.getData().get(i).getPaymentMethod()).getPaymentMethodAppInPaymentsEntity().getApp()).getProvider());
                }`

**Comment by naved997** [comment] 2024-05-08 12:57
Yes Suhas you are right the code only works for wallet payments

**Comment by suhas-cashfree** [comment] 2024-05-08 12:58
Check for which instance and then use specific code. 
Closing this for now. Please raise a new ticket if it still persists

**Closed by suhas-cashfree** 2024-05-08 12:58 UTC
